services:
  tesnix:
    image: luckys2008/tesnix:v3.2
    container_name: tesnix
    volumes:
      - ${XAUTHORITY}:${XAUTHORITY}:ro
      - ./:/tesnix
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
    stdin_open: true
    tty: true