services:
  tesnix:
    build:
      context: .
      dockerfile: Dockerfile
    image: luckys2008/tesnix:v4
    container_name: tesnix
    hostname: tesnix
    volumes:
      - ${XAUTHORITY}:/tmp/.Xauthority
      - ./:/tesnix
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority
    stdin_open: true
    tty: true