.extern common_handler
.macro irq_stub num
.global irq_stub_\num

irq_stub_\num:
    pushl $0
    pushl $\num
    pushal
    movl %esp, %eax
    pushl %eax
    call common_handler
    addl $4, %esp
    popal
    addl $8, %esp
    iret

.endm

# autogenerated irqs

irq_stub 0
irq_stub 1
irq_stub 2
irq_stub 3
irq_stub 4
irq_stub 5
irq_stub 6
irq_stub 7
irq_stub 8
irq_stub 9
irq_stub 10
irq_stub 11
irq_stub 12
irq_stub 13
irq_stub 14
irq_stub 15

.global irq_stub_table
irq_stub_table:
    .long irq_stub_0
    .long irq_stub_1
    .long irq_stub_2
    .long irq_stub_3
    .long irq_stub_4
    .long irq_stub_5
    .long irq_stub_6
    .long irq_stub_7
    .long irq_stub_8
    .long irq_stub_9
    .long irq_stub_10
    .long irq_stub_11
    .long irq_stub_12
    .long irq_stub_13
    .long irq_stub_14
    .long irq_stub_15
